name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Run Infracost Breakdown
        env:
          #INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          INFRACOST_API_KEY: ico-5dkInRidKyoErtXV38k4r6SuEQNTIOB3
        run: |
          infracost breakdown --path=. --format=table

  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Checkov Scan
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        quiet: false

    - name: Terraform Plan
      run: terraform plan -input=false
